/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContactModel } from './contact-model';
import { UserViewModel } from './user-view-model';

/**
 * 
 * @export
 * @interface AccountModel
 */
export interface AccountModel {
    /**
     * 
     * @type {UserViewModel}
     * @memberof AccountModel
     */
    'accountCreateUserModel'?: UserViewModel;
    /**
     * 
     * @type {string}
     * @memberof AccountModel
     */
    'accountDescription'?: string;
    /**
     * 
     * @type {number}
     * @memberof AccountModel
     */
    'accountId'?: number;
    /**
     * 
     * @type {string}
     * @memberof AccountModel
     */
    'accountName'?: string;
    /**
     * 
     * @type {ContactModel}
     * @memberof AccountModel
     */
    'accountOwnerModel'?: ContactModel;
    /**
     * 
     * @type {number}
     * @memberof AccountModel
     */
    'cid'?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountModel
     */
    'id'?: number;
}

