/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AssessmentRangeModel
 */
export interface AssessmentRangeModel {
    /**
     * 
     * @type {string}
     * @memberof AssessmentRangeModel
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof AssessmentRangeModel
     */
    'cid'?: number;
    /**
     * 
     * @type {string}
     * @memberof AssessmentRangeModel
     */
    'colorCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof AssessmentRangeModel
     */
    'interpretation'?: string;
    /**
     * 
     * @type {number}
     * @memberof AssessmentRangeModel
     */
    'rangeMax'?: number;
    /**
     * 
     * @type {number}
     * @memberof AssessmentRangeModel
     */
    'rangeMin'?: number;
    /**
     * 
     * @type {number}
     * @memberof AssessmentRangeModel
     */
    'scoreTempId'?: number;
    /**
     * 
     * @type {number}
     * @memberof AssessmentRangeModel
     */
    'strangeid'?: number;
}

