/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AttachmentFolderModel
 */
export interface AttachmentFolderModel {
    /**
     * 
     * @type {number}
     * @memberof AttachmentFolderModel
     */
    'atchFolderId'?: number;
    /**
     * 
     * @type {string}
     * @memberof AttachmentFolderModel
     */
    'atchFolderName'?: string;
    /**
     * 
     * @type {number}
     * @memberof AttachmentFolderModel
     */
    'cid'?: number;
    /**
     * 
     * @type {number}
     * @memberof AttachmentFolderModel
     */
    'createuserid'?: number;
    /**
     * 
     * @type {number}
     * @memberof AttachmentFolderModel
     */
    'usedCount'?: number;
}

