/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AttachmentFolderModel } from './attachment-folder-model';
import { ObjectAccessModel } from './object-access-model';
import { ProjectModel } from './project-model';
import { StateCountryModel } from './state-country-model';
import { UserGroupModel } from './user-group-model';
import { UserModel } from './user-model';

/**
 * 
 * @export
 * @interface AttachmentModel
 */
export interface AttachmentModel {
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'access'?: string;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'annId'?: number;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'appraisalAssignmentId'?: number;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'appraisalItemResponseId'?: number;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'appraisalid'?: number;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'assetid'?: number;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'atchType'?: string;
    /**
     * 
     * @type {UserModel}
     * @memberof AttachmentModel
     */
    'attachUserModel'?: UserModel;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'attachid'?: number;
    /**
     * 
     * @type {AttachmentFolderModel}
     * @memberof AttachmentModel
     */
    'attachmentFolderModel'?: AttachmentFolderModel;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'authkey'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AttachmentModel
     */
    'candidateAccess'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'candidateid'?: number;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'category'?: string;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'cid'?: number;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'comments'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'createts'?: string;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'createuserid'?: number;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'customerId'?: number;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'dLExpiryDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'dLIssueDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'documentContent'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'documentExpiryDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'documentType'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'documnetIssueDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'expenseItemId'?: number;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'expenseid'?: number;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'fileExtn'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'filename'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'folder'?: string;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'folder_id'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AttachmentModel
     */
    'global'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'goalid'?: number;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'language'?: string;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'leaveid'?: number;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'multiSigning'?: number;
    /**
     * 
     * @type {Array<ObjectAccessModel>}
     * @memberof AttachmentModel
     */
    'objectAccessModelList'?: Array<ObjectAccessModel>;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'objectType'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'obtype'?: string;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'payStubId'?: number;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'positionid'?: number;
    /**
     * 
     * @type {ProjectModel}
     * @memberof AttachmentModel
     */
    'projectModel'?: ProjectModel;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'projectid'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AttachmentModel
     */
    'resume'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'ruleid'?: number;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    's3id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'signNowDocId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'signNowTemplateId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'signStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'signatureId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'signatureRequestId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'signingDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'size'?: number;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'skilluserId'?: number;
    /**
     * 
     * @type {StateCountryModel}
     * @memberof AttachmentModel
     */
    'stateCountryModel'?: StateCountryModel;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'taskId'?: number;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'ticketId'?: number;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'timecardid'?: number;
    /**
     * 
     * @type {string}
     * @memberof AttachmentModel
     */
    'topic'?: string;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'trainingId'?: number;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'userAccess'?: number;
    /**
     * 
     * @type {UserGroupModel}
     * @memberof AttachmentModel
     */
    'userGroupModel'?: UserGroupModel;
    /**
     * 
     * @type {UserModel}
     * @memberof AttachmentModel
     */
    'userModel'?: UserModel;
    /**
     * 
     * @type {number}
     * @memberof AttachmentModel
     */
    'userid'?: number;
}

