/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BankAccountModel
 */
export interface BankAccountModel {
    /**
     * 
     * @type {string}
     * @memberof BankAccountModel
     */
    'accountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountModel
     */
    'accountNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountModel
     */
    'accountType'?: string;
    /**
     * 
     * @type {number}
     * @memberof BankAccountModel
     */
    'bankAccountId'?: number;
    /**
     * 
     * @type {number}
     * @memberof BankAccountModel
     */
    'bankCountryId'?: number;
    /**
     * 
     * @type {string}
     * @memberof BankAccountModel
     */
    'branchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountModel
     */
    'branchName'?: string;
    /**
     * 
     * @type {number}
     * @memberof BankAccountModel
     */
    'cid'?: number;
    /**
     * 
     * @type {number}
     * @memberof BankAccountModel
     */
    'countryId'?: number;
    /**
     * 
     * @type {number}
     * @memberof BankAccountModel
     */
    'createUserId'?: number;
    /**
     * 
     * @type {string}
     * @memberof BankAccountModel
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountModel
     */
    'ownerType'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountModel
     */
    'paymentEmail'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountModel
     */
    'routingNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountModel
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountModel
     */
    'swiftCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof BankAccountModel
     */
    'userId'?: number;
}

