/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CandidatesGetCandidateDetailByRecruitidResponseData
 */
export interface CandidatesGetCandidateDetailByRecruitidResponseData {
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'recruitId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'referrerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'referrer'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'recruiter'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'score'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'updatedOn'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'notes'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'dateOfBirth'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'joiningDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'createts'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'templateId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'recruiterUserId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'workflowId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'statusid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'workflowModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'candidateStatusModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'assessmentModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'workflowName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'employmentModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'educationModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'customFieldValueModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'addressModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'skillModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'positionName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'candidatePositionsModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'createuserid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'lastupdateuserid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'accessCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'source'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'passwordHash'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'acceptance1'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'acceptance2'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'summaryByCandidate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'systemReco'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'systemRecoHelp'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'candidateLock'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'salaryCurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'salaryAmount'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'educationStr'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'languagePreference'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'verified'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'verificationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'isInternalCand'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'isNewCand'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'timezone'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'trainingAccess'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'customfieldvalue'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'cloudSearchSync'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'jobBoardAccess'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'bgScreeningOrderGuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'bgScreeningOrderCreateDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'checkrCandidateId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'positionModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'certificationModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetCandidateDetailByRecruitidResponseData
     */
    'attachmentModelList'?: string;
}

