/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CandidatesGetBasicDetailsResponseDataInner
 */
export interface CandidatesGetBasicDetailsResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'recruitId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'dateOfBirth'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'statusid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'referrerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'createts'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'notes'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'source'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'userid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'recruiterUserId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'summaryByCandidate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'candidateLock'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'educationStr'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'appliedPositions'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'updatedOn'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'tagIds'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'statusColor'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'appliedPositionIds'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'appliedPositionUids'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'recruiterThumbnail'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'recruiterName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'recruiterGender'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'referrerName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'isInternalCand'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'applicationStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'verified'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'positionNameList'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponseDataInner
     */
    'internalCandidate'?: string;
}

