/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface CandidateApplicationsModel
 */
export interface CandidateApplicationsModel {
    /**
     * 
     * @type {string}
     * @memberof CandidateApplicationsModel
     */
    'applicationDueDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof CandidateApplicationsModel
     */
    'applicationStatusId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CandidateApplicationsModel
     */
    'applicationStatusValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateApplicationsModel
     */
    'appliedPositions'?: string;
    /**
     * 
     * @type {number}
     * @memberof CandidateApplicationsModel
     */
    'candidateId'?: number;
    /**
     * 
     * @type {Timestamp}
     * @memberof CandidateApplicationsModel
     */
    'candidatePositionCreateTs'?: Timestamp;
    /**
     * 
     * @type {number}
     * @memberof CandidateApplicationsModel
     */
    'candidatePositionsId'?: number;
    /**
     * 
     * @type {number}
     * @memberof CandidateApplicationsModel
     */
    'cid'?: number;
    /**
     * 
     * @type {string}
     * @memberof CandidateApplicationsModel
     */
    'colorcode'?: string;
    /**
     * 
     * @type {number}
     * @memberof CandidateApplicationsModel
     */
    'count'?: number;
    /**
     * 
     * @type {number}
     * @memberof CandidateApplicationsModel
     */
    'positionDepartmentId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CandidateApplicationsModel
     */
    'positionDescription'?: string;
    /**
     * 
     * @type {number}
     * @memberof CandidateApplicationsModel
     */
    'positionLocationId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CandidateApplicationsModel
     */
    'positionName'?: string;
    /**
     * 
     * @type {number}
     * @memberof CandidateApplicationsModel
     */
    'positionProfileId'?: number;
    /**
     * 
     * @type {number}
     * @memberof CandidateApplicationsModel
     */
    'positionProjectId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CandidateApplicationsModel
     */
    'positionStatusOpenClosed'?: string;
    /**
     * 
     * @type {Timestamp}
     * @memberof CandidateApplicationsModel
     */
    'positioncreatets'?: Timestamp;
    /**
     * 
     * @type {number}
     * @memberof CandidateApplicationsModel
     */
    'positionid'?: number;
    /**
     * 
     * @type {string}
     * @memberof CandidateApplicationsModel
     */
    'responsibilities'?: string;
    /**
     * 
     * @type {number}
     * @memberof CandidateApplicationsModel
     */
    'sequence'?: number;
    /**
     * 
     * @type {string}
     * @memberof CandidateApplicationsModel
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateApplicationsModel
     */
    'systemReco'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateApplicationsModel
     */
    'systemRecoHelp'?: string;
}

