/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CandidatesGetResponseDataInnerCandidatePositionsModelListInner } from './candidates-get-response-data-inner-candidate-positions-model-list-inner';

/**
 * 
 * @export
 * @interface CandidatesGetResponseDataInner
 */
export interface CandidatesGetResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'recruitId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'referrerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'referrer'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'recruiter'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'score'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'updatedOn'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'notes'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'dateOfBirth'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'joiningDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'createts'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'templateId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'recruiterUserId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'workflowId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'statusid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'workflowModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'candidateStatusModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'assessmentModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'workflowName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'employmentModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'educationModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'customFieldValueModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'addressModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'skillModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'positionName'?: string;
    /**
     * 
     * @type {Array<CandidatesGetResponseDataInnerCandidatePositionsModelListInner>}
     * @memberof CandidatesGetResponseDataInner
     */
    'candidatePositionsModelList'?: Array<CandidatesGetResponseDataInnerCandidatePositionsModelListInner>;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'createuserid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'lastupdateuserid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'accessCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'source'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'passwordHash'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'acceptance1'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'acceptance2'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'summaryByCandidate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'systemReco'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'systemRecoHelp'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'candidateLock'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'salaryCurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'salaryAmount'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'educationStr'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'languagePreference'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'verified'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'verificationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'isInternalCand'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'isNewCand'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'timezone'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'trainingAccess'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'customfieldvalue'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'cloudSearchSync'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'jobBoardAccess'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'bgScreeningOrderGuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'bgScreeningOrderCreateDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'checkrCandidateId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'positionModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'certificationModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInner
     */
    'attachmentModelList'?: string;
}

