/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddressModel } from './address-model';
import { AssessmentModel } from './assessment-model';
import { AttachmentModel } from './attachment-model';
import { CandidateApplicationsModel } from './candidate-applications-model';
import { CandidateStatusModel } from './candidate-status-model';
import { CertificationModel } from './certification-model';
import { CustomFieldValueModel } from './custom-field-value-model';
import { EducationModel } from './education-model';
import { EmploymentModel } from './employment-model';
import { PositionModel } from './position-model';
import { SkillUserModel } from './skill-user-model';
import { Timestamp } from './timestamp';
import { WorkflowModel } from './workflow-model';

/**
 * 
 * @export
 * @interface CandidateModel
 */
export interface CandidateModel {
    /**
     * 
     * @type {boolean}
     * @memberof CandidateModel
     */
    'acceptance1'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CandidateModel
     */
    'acceptance2'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'accessCode'?: string;
    /**
     * 
     * @type {Array<AddressModel>}
     * @memberof CandidateModel
     */
    'addressModelList'?: Array<AddressModel>;
    /**
     * 
     * @type {AssessmentModel}
     * @memberof CandidateModel
     */
    'assessmentModel'?: AssessmentModel;
    /**
     * 
     * @type {Array<AttachmentModel>}
     * @memberof CandidateModel
     */
    'attachmentModelList'?: Array<AttachmentModel>;
    /**
     * 
     * @type {number}
     * @memberof CandidateModel
     */
    'candidateLock'?: number;
    /**
     * 
     * @type {Array<CandidateApplicationsModel>}
     * @memberof CandidateModel
     */
    'candidatePositionsModelList'?: Array<CandidateApplicationsModel>;
    /**
     * 
     * @type {CandidateStatusModel}
     * @memberof CandidateModel
     */
    'candidateStatusModel'?: CandidateStatusModel;
    /**
     * 
     * @type {Array<CertificationModel>}
     * @memberof CandidateModel
     */
    'certificationModelList'?: Array<CertificationModel>;
    /**
     * 
     * @type {number}
     * @memberof CandidateModel
     */
    'cid'?: number;
    /**
     * 
     * @type {number}
     * @memberof CandidateModel
     */
    'cloudSearchSync'?: number;
    /**
     * 
     * @type {Timestamp}
     * @memberof CandidateModel
     */
    'createts'?: Timestamp;
    /**
     * 
     * @type {number}
     * @memberof CandidateModel
     */
    'createuserid'?: number;
    /**
     * 
     * @type {Array<CustomFieldValueModel>}
     * @memberof CandidateModel
     */
    'customFieldValueModelList'?: Array<CustomFieldValueModel>;
    /**
     * 
     * @type {Array<CustomFieldValueModel>}
     * @memberof CandidateModel
     */
    'customfieldvalue'?: Array<CustomFieldValueModel>;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'dateOfBirth'?: string;
    /**
     * 
     * @type {Array<EducationModel>}
     * @memberof CandidateModel
     */
    'educationModelList'?: Array<EducationModel>;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'educationStr'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'email'?: string;
    /**
     * 
     * @type {Array<EmploymentModel>}
     * @memberof CandidateModel
     */
    'employmentModelList'?: Array<EmploymentModel>;
    /**
     * 
     * @type {boolean}
     * @memberof CandidateModel
     */
    'isInternalCand'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CandidateModel
     */
    'isNewCand'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'languagePreference'?: string;
    /**
     * 
     * @type {number}
     * @memberof CandidateModel
     */
    'lastupdateuserid'?: number;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'notes'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'passwordHash'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'phone'?: string;
    /**
     * 
     * @type {PositionModel}
     * @memberof CandidateModel
     */
    'positionModel'?: PositionModel;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'positionName'?: string;
    /**
     * 
     * @type {number}
     * @memberof CandidateModel
     */
    'recruitId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'recruiter'?: string;
    /**
     * 
     * @type {number}
     * @memberof CandidateModel
     */
    'recruiterUserId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'referrer'?: string;
    /**
     * 
     * @type {number}
     * @memberof CandidateModel
     */
    'referrerId'?: number;
    /**
     * 
     * @type {number}
     * @memberof CandidateModel
     */
    'salaryAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'salaryCurrencyCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof CandidateModel
     */
    'score'?: number;
    /**
     * 
     * @type {Array<SkillUserModel>}
     * @memberof CandidateModel
     */
    'skillModelList'?: Array<SkillUserModel>;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'source'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof CandidateModel
     */
    'statusid'?: number;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'summaryByCandidate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'systemReco'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'systemRecoHelp'?: string;
    /**
     * 
     * @type {number}
     * @memberof CandidateModel
     */
    'templateId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'timezone'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CandidateModel
     */
    'trainingAccess'?: boolean;
    /**
     * 
     * @type {Timestamp}
     * @memberof CandidateModel
     */
    'updatedOn'?: Timestamp;
    /**
     * 
     * @type {number}
     * @memberof CandidateModel
     */
    'userId'?: number;
    /**
     * 
     * @type {number}
     * @memberof CandidateModel
     */
    'verificationCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'verified'?: string;
    /**
     * 
     * @type {number}
     * @memberof CandidateModel
     */
    'workflowId'?: number;
    /**
     * 
     * @type {WorkflowModel}
     * @memberof CandidateModel
     */
    'workflowModel'?: WorkflowModel;
    /**
     * 
     * @type {string}
     * @memberof CandidateModel
     */
    'workflowName'?: string;
}

