/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CandidatesGetBasicDetailsResponseDataInner } from './candidates-get-basic-details-response-data-inner';

/**
 * 
 * @export
 * @interface CandidatesGetBasicDetailsResponse
 */
export interface CandidatesGetBasicDetailsResponse {
    /**
     * 
     * @type {Array<CandidatesGetBasicDetailsResponseDataInner>}
     * @memberof CandidatesGetBasicDetailsResponse
     */
    'data'?: Array<CandidatesGetBasicDetailsResponseDataInner>;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetBasicDetailsResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CandidatesGetBasicDetailsResponse
     */
    'editPermission'?: boolean;
}

