/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CandidatesGetResponseDataInnerCandidatePositionsModelListInner
 */
export interface CandidatesGetResponseDataInnerCandidatePositionsModelListInner {
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'candidatePositionsId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'candidateId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'positionid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'positionName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'positionDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'responsibilities'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'positionDepartmentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'positionLocationId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'positionProjectId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'positionProfileId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'count'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'positioncreatets'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'positionStatusOpenClosed'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'applicationDueDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'applicationStatusId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'applicationStatusValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'sequence'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'colorcode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'systemReco'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'systemRecoHelp'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'candidatePositionCreateTs'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'appliedPositions'?: string;
    /**
     * 
     * @type {string}
     * @memberof CandidatesGetResponseDataInnerCandidatePositionsModelListInner
     */
    'status'?: string;
}

