/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CandidatesExtractPdfResumeRequest
 */
export interface CandidatesExtractPdfResumeRequest {
    /**
     * The pdf resume of the candidate.
     * @type {Uint8Array | File | buffer.File}
     * @memberof CandidatesExtractPdfResumeRequest
     */
    'file': Uint8Array | File | buffer.File;
}

