/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface CertificationModel
 */
export interface CertificationModel {
    /**
     * 
     * @type {string}
     * @memberof CertificationModel
     */
    'CertificationNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof CertificationModel
     */
    'authority'?: string;
    /**
     * 
     * @type {number}
     * @memberof CertificationModel
     */
    'candidateId'?: number;
    /**
     * 
     * @type {number}
     * @memberof CertificationModel
     */
    'certificationId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CertificationModel
     */
    'certificationNumber'?: string;
    /**
     * 
     * @type {number}
     * @memberof CertificationModel
     */
    'cid'?: number;
    /**
     * 
     * @type {string}
     * @memberof CertificationModel
     */
    'comments'?: string;
    /**
     * 
     * @type {number}
     * @memberof CertificationModel
     */
    'createUserId'?: number;
    /**
     * 
     * @type {Timestamp}
     * @memberof CertificationModel
     */
    'createts'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof CertificationModel
     */
    'expireDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CertificationModel
     */
    'issueDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CertificationModel
     */
    'issueState'?: string;
    /**
     * 
     * @type {string}
     * @memberof CertificationModel
     */
    'type'?: string;
    /**
     * 
     * @type {number}
     * @memberof CertificationModel
     */
    'userId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CertificationModel
     */
    'validState'?: string;
}

