/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CurrencyModel
 */
export interface CurrencyModel {
    /**
     * 
     * @type {number}
     * @memberof CurrencyModel
     */
    'cid'?: number;
    /**
     * 
     * @type {string}
     * @memberof CurrencyModel
     */
    'currencyCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof CurrencyModel
     */
    'currencyId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CurrencyModel
     */
    'currencyName'?: string;
}

