/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomFieldsGetCustomListsResponseInnerCustomListEntryModelInner } from './custom-fields-get-custom-lists-response-inner-custom-list-entry-model-inner';

/**
 * 
 * @export
 * @interface CustomFieldsGetCustomListsResponseInner
 */
export interface CustomFieldsGetCustomListsResponseInner {
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetCustomListsResponseInner
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetCustomListsResponseInner
     */
    'listId'?: string;
    /**
     * 
     * @type {Array<CustomFieldsGetCustomListsResponseInnerCustomListEntryModelInner>}
     * @memberof CustomFieldsGetCustomListsResponseInner
     */
    'customListEntryModel'?: Array<CustomFieldsGetCustomListsResponseInnerCustomListEntryModelInner>;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetCustomListsResponseInner
     */
    'listName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetCustomListsResponseInner
     */
    'cid'?: string;
}

