/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface CustomFieldGroupModel
 */
export interface CustomFieldGroupModel {
    /**
     * 
     * @type {string}
     * @memberof CustomFieldGroupModel
     */
    'access'?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomFieldGroupModel
     */
    'cfgroupid'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldGroupModel
     */
    'cfgroupname'?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomFieldGroupModel
     */
    'cid'?: number;
    /**
     * 
     * @type {Timestamp}
     * @memberof CustomFieldGroupModel
     */
    'createts'?: Timestamp;
    /**
     * 
     * @type {boolean}
     * @memberof CustomFieldGroupModel
     */
    'hasCustomFields'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldGroupModel
     */
    'layout'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldGroupModel
     */
    'objectType'?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomFieldGroupModel
     */
    'sequence'?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomFieldGroupModel
     */
    'usergroupid'?: number;
}

