/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomFieldsGetByIdResponseDataCustomFieldGroupModel } from './custom-fields-get-by-id-response-data-custom-field-group-model';
import { CustomFieldsGetByIdResponseDataCustomFieldValueModelListInner } from './custom-fields-get-by-id-response-data-custom-field-value-model-list-inner';

/**
 * 
 * @export
 * @interface CustomFieldsGetByIdResponseData
 */
export interface CustomFieldsGetByIdResponseData {
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'customFieldId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'customFieldName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'customFieldType'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'objectType'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'sequence'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'fieldType'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'defaultValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'cfcode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'cfgroupid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'style'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'opValues'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'fieldFormula'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'customFieldValueModel'?: string;
    /**
     * 
     * @type {Array<CustomFieldsGetByIdResponseDataCustomFieldValueModelListInner>}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'customFieldValueModelList'?: Array<CustomFieldsGetByIdResponseDataCustomFieldValueModelListInner>;
    /**
     * 
     * @type {CustomFieldsGetByIdResponseDataCustomFieldGroupModel}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'customFieldGroupModel'?: CustomFieldsGetByIdResponseDataCustomFieldGroupModel;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'objectAccessModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'access'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'userGroupId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'candidateAccess'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'userAccess'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'managerAccess'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'integrationTypeId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'helpText'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'createUserId'?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'createts'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'customFieldStyleModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'readAccessTypeCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'readUserGroupId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'mandatory'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsGetByIdResponseData
     */
    'masked'?: string;
}

