/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomListEntryModel } from './custom-list-entry-model';

/**
 * 
 * @export
 * @interface CustomListModel
 */
export interface CustomListModel {
    /**
     * 
     * @type {string}
     * @memberof CustomListModel
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomListModel
     */
    'cid'?: number;
    /**
     * 
     * @type {Array<CustomListEntryModel>}
     * @memberof CustomListModel
     */
    'customListEntryModel'?: Array<CustomListEntryModel>;
    /**
     * 
     * @type {number}
     * @memberof CustomListModel
     */
    'listId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomListModel
     */
    'listName'?: string;
}

