/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomTableColumnModel } from './custom-table-column-model';
import { CustomTableValueModel } from './custom-table-value-model';
import { Timestamp } from './timestamp';
import { UserGroupModel } from './user-group-model';
import { UserModel } from './user-model';

/**
 * 
 * @export
 * @interface CustomTableModel
 */
export interface CustomTableModel {
    /**
     * 
     * @type {string}
     * @memberof CustomTableModel
     */
    'candidateAccess'?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomTableModel
     */
    'cid'?: number;
    /**
     * 
     * @type {UserModel}
     * @memberof CustomTableModel
     */
    'createUserModel'?: UserModel;
    /**
     * 
     * @type {Timestamp}
     * @memberof CustomTableModel
     */
    'createts'?: Timestamp;
    /**
     * 
     * @type {Array<CustomTableColumnModel>}
     * @memberof CustomTableModel
     */
    'ctColumnList'?: Array<CustomTableColumnModel>;
    /**
     * 
     * @type {Array<CustomTableValueModel>}
     * @memberof CustomTableModel
     */
    'ctValueList'?: Array<CustomTableValueModel>;
    /**
     * 
     * @type {number}
     * @memberof CustomTableModel
     */
    'customTableId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomTableModel
     */
    'helpText'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomTableModel
     */
    'objectType'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomTableModel
     */
    'readAccess'?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomTableModel
     */
    'readUserGroupId'?: number;
    /**
     * 
     * @type {UserGroupModel}
     * @memberof CustomTableModel
     */
    'readUserGroupModel'?: UserGroupModel;
    /**
     * 
     * @type {number}
     * @memberof CustomTableModel
     */
    'sequence'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomTableModel
     */
    'tableName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomTableModel
     */
    'userAccess'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomTableModel
     */
    'writeAccess'?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomTableModel
     */
    'writeUserGroupId'?: number;
    /**
     * 
     * @type {UserGroupModel}
     * @memberof CustomTableModel
     */
    'writeUserGroupModel'?: UserGroupModel;
}

