/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DocumentLibraryGetDocumentAsByteArrayResponse
 */
export interface DocumentLibraryGetDocumentAsByteArrayResponse {
    /**
     * 
     * @type {number}
     * @memberof DocumentLibraryGetDocumentAsByteArrayResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentLibraryGetDocumentAsByteArrayResponse
     */
    'data'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentLibraryGetDocumentAsByteArrayResponse
     */
    'message'?: string;
}

