/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Timestamp } from './timestamp';
import { UserGroupModel } from './user-group-model';
import { UserModel } from './user-model';
import { UserViewModel } from './user-view-model';

/**
 * 
 * @export
 * @interface DynaFormSlimModel
 */
export interface DynaFormSlimModel {
    /**
     * 
     * @type {string}
     * @memberof DynaFormSlimModel
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof DynaFormSlimModel
     */
    'anonymous'?: number;
    /**
     * 
     * @type {string}
     * @memberof DynaFormSlimModel
     */
    'attemptLimit'?: string;
    /**
     * 
     * @type {string}
     * @memberof DynaFormSlimModel
     */
    'availability'?: string;
    /**
     * 
     * @type {number}
     * @memberof DynaFormSlimModel
     */
    'cid'?: number;
    /**
     * 
     * @type {UserModel}
     * @memberof DynaFormSlimModel
     */
    'createUserModel'?: UserModel;
    /**
     * 
     * @type {UserViewModel}
     * @memberof DynaFormSlimModel
     */
    'createUserViewModel'?: UserViewModel;
    /**
     * 
     * @type {Timestamp}
     * @memberof DynaFormSlimModel
     */
    'createts'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof DynaFormSlimModel
     */
    'dataFlow'?: string;
    /**
     * 
     * @type {string}
     * @memberof DynaFormSlimModel
     */
    'dynaFormCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof DynaFormSlimModel
     */
    'dynamicFormId'?: number;
    /**
     * 
     * @type {string}
     * @memberof DynaFormSlimModel
     */
    'formType'?: string;
    /**
     * 
     * @type {string}
     * @memberof DynaFormSlimModel
     */
    'layout'?: string;
    /**
     * 
     * @type {string}
     * @memberof DynaFormSlimModel
     */
    'mappedEntity'?: string;
    /**
     * 
     * @type {string}
     * @memberof DynaFormSlimModel
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DynaFormSlimModel
     */
    'presentationStyle'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DynaFormSlimModel
     */
    'publicSummary'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DynaFormSlimModel
     */
    'secSequence'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DynaFormSlimModel
     */
    'showCorrect'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DynaFormSlimModel
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof DynaFormSlimModel
     */
    'thresholdScore'?: number;
    /**
     * 
     * @type {number}
     * @memberof DynaFormSlimModel
     */
    'timeLimit'?: number;
    /**
     * 
     * @type {Timestamp}
     * @memberof DynaFormSlimModel
     */
    'updatets'?: Timestamp;
    /**
     * 
     * @type {UserGroupModel}
     * @memberof DynaFormSlimModel
     */
    'userGroupModel'?: UserGroupModel;
}

