/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DynamicFormAssignmentModel } from './dynamic-form-assignment-model';
import { DynamicFormSectionModel } from './dynamic-form-section-model';
import { Timestamp } from './timestamp';
import { UserGroupModel } from './user-group-model';
import { UserViewModel } from './user-view-model';

/**
 * 
 * @export
 * @interface DynaFormSectionAssignmentModel
 */
export interface DynaFormSectionAssignmentModel {
    /**
     * 
     * @type {string}
     * @memberof DynaFormSectionAssignmentModel
     */
    'assigneeRole'?: string;
    /**
     * 
     * @type {number}
     * @memberof DynaFormSectionAssignmentModel
     */
    'cid'?: number;
    /**
     * 
     * @type {UserViewModel}
     * @memberof DynaFormSectionAssignmentModel
     */
    'completedBy'?: UserViewModel;
    /**
     * 
     * @type {Timestamp}
     * @memberof DynaFormSectionAssignmentModel
     */
    'createts'?: Timestamp;
    /**
     * 
     * @type {number}
     * @memberof DynaFormSectionAssignmentModel
     */
    'dynaFormSectionAssignId'?: number;
    /**
     * 
     * @type {DynamicFormAssignmentModel}
     * @memberof DynaFormSectionAssignmentModel
     */
    'dynamicFormAssignmentModel'?: DynamicFormAssignmentModel;
    /**
     * 
     * @type {DynamicFormSectionModel}
     * @memberof DynaFormSectionAssignmentModel
     */
    'dynamicFormSectionModel'?: DynamicFormSectionModel;
    /**
     * 
     * @type {string}
     * @memberof DynaFormSectionAssignmentModel
     */
    'status'?: string;
    /**
     * 
     * @type {UserGroupModel}
     * @memberof DynaFormSectionAssignmentModel
     */
    'userGroupModel'?: UserGroupModel;
    /**
     * 
     * @type {UserViewModel}
     * @memberof DynaFormSectionAssignmentModel
     */
    'userViewModel'?: UserViewModel;
}

