/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface DynaFormItemOptionModel
 */
export interface DynaFormItemOptionModel {
    /**
     * 
     * @type {number}
     * @memberof DynaFormItemOptionModel
     */
    'cid'?: number;
    /**
     * 
     * @type {Timestamp}
     * @memberof DynaFormItemOptionModel
     */
    'createts'?: Timestamp;
    /**
     * 
     * @type {number}
     * @memberof DynaFormItemOptionModel
     */
    'dynaFormItemId'?: number;
    /**
     * 
     * @type {number}
     * @memberof DynaFormItemOptionModel
     */
    'optionId'?: number;
    /**
     * 
     * @type {string}
     * @memberof DynaFormItemOptionModel
     */
    'optionValue'?: string;
}

