/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AttachmentModel } from './attachment-model';
import { CustomListModel } from './custom-list-model';
import { DynaFormItemOptionModel } from './dyna-form-item-option-model';
import { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface DynamicFormItemModel
 */
export interface DynamicFormItemModel {
    /**
     * 
     * @type {AttachmentModel}
     * @memberof DynamicFormItemModel
     */
    'attachmentModel'?: AttachmentModel;
    /**
     * 
     * @type {number}
     * @memberof DynamicFormItemModel
     */
    'cid'?: number;
    /**
     * 
     * @type {string}
     * @memberof DynamicFormItemModel
     */
    'correctFeedback'?: string;
    /**
     * 
     * @type {number}
     * @memberof DynamicFormItemModel
     */
    'createUserId'?: number;
    /**
     * 
     * @type {Timestamp}
     * @memberof DynamicFormItemModel
     */
    'createts'?: Timestamp;
    /**
     * 
     * @type {CustomListModel}
     * @memberof DynamicFormItemModel
     */
    'customListModel'?: CustomListModel;
    /**
     * 
     * @type {Array<DynaFormItemOptionModel>}
     * @memberof DynamicFormItemModel
     */
    'dynaFormItemOptionModelList'?: Array<DynaFormItemOptionModel>;
    /**
     * 
     * @type {number}
     * @memberof DynamicFormItemModel
     */
    'dynamicFormId'?: number;
    /**
     * 
     * @type {number}
     * @memberof DynamicFormItemModel
     */
    'dynamicFormItemId'?: number;
    /**
     * 
     * @type {string}
     * @memberof DynamicFormItemModel
     */
    'expectedValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicFormItemModel
     */
    'fieldType'?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicFormItemModel
     */
    'fieldTypeItem'?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicFormItemModel
     */
    'helpText'?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicFormItemModel
     */
    'incorrectFeedback'?: string;
    /**
     * 
     * @type {number}
     * @memberof DynamicFormItemModel
     */
    'mandatory'?: number;
    /**
     * 
     * @type {string}
     * @memberof DynamicFormItemModel
     */
    'mappedEntityItem'?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicFormItemModel
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DynamicFormItemModel
     */
    'numberingStyle'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DynamicFormItemModel
     */
    'optionRandom'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DynamicFormItemModel
     */
    'optionValues'?: string;
    /**
     * 
     * @type {number}
     * @memberof DynamicFormItemModel
     */
    'sectionId'?: number;
    /**
     * 
     * @type {number}
     * @memberof DynamicFormItemModel
     */
    'sequence'?: number;
    /**
     * 
     * @type {number}
     * @memberof DynamicFormItemModel
     */
    'weightage'?: number;
}

