/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface EducationModel
 */
export interface EducationModel {
    /**
     * 
     * @type {number}
     * @memberof EducationModel
     */
    'cid'?: number;
    /**
     * 
     * @type {string}
     * @memberof EducationModel
     */
    'city'?: string;
    /**
     * 
     * @type {number}
     * @memberof EducationModel
     */
    'countryId'?: number;
    /**
     * 
     * @type {string}
     * @memberof EducationModel
     */
    'course'?: string;
    /**
     * 
     * @type {Timestamp}
     * @memberof EducationModel
     */
    'createts'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof EducationModel
     */
    'degree'?: string;
    /**
     * 
     * @type {number}
     * @memberof EducationModel
     */
    'degreeId'?: number;
    /**
     * 
     * @type {string}
     * @memberof EducationModel
     */
    'degreeType'?: string;
    /**
     * 
     * @type {number}
     * @memberof EducationModel
     */
    'educationId'?: number;
    /**
     * 
     * @type {string}
     * @memberof EducationModel
     */
    'endDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof EducationModel
     */
    'expirationDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof EducationModel
     */
    'gpa'?: string;
    /**
     * 
     * @type {number}
     * @memberof EducationModel
     */
    'graduation'?: number;
    /**
     * 
     * @type {string}
     * @memberof EducationModel
     */
    'institution'?: string;
    /**
     * 
     * @type {number}
     * @memberof EducationModel
     */
    'institutionId'?: number;
    /**
     * 
     * @type {number}
     * @memberof EducationModel
     */
    'isHighest'?: number;
    /**
     * 
     * @type {number}
     * @memberof EducationModel
     */
    'profileid'?: number;
    /**
     * 
     * @type {number}
     * @memberof EducationModel
     */
    'recruitid'?: number;
    /**
     * 
     * @type {string}
     * @memberof EducationModel
     */
    'startDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof EducationModel
     */
    'state'?: string;
    /**
     * 
     * @type {number}
     * @memberof EducationModel
     */
    'userId'?: number;
}

