/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExpenseReportsGetCurrenciesResponseDataInner } from './expense-reports-get-currencies-response-data-inner';

/**
 * 
 * @export
 * @interface ExpenseReportsGetCurrenciesResponse
 */
export interface ExpenseReportsGetCurrenciesResponse {
    /**
     * 
     * @type {Array<ExpenseReportsGetCurrenciesResponseDataInner>}
     * @memberof ExpenseReportsGetCurrenciesResponse
     */
    'data'?: Array<ExpenseReportsGetCurrenciesResponseDataInner>;
    /**
     * 
     * @type {string}
     * @memberof ExpenseReportsGetCurrenciesResponse
     */
    'message'?: string;
}

