/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ExpenseReportsCreateNewResponse
 */
export interface ExpenseReportsCreateNewResponse {
    /**
     * 
     * @type {string}
     * @memberof ExpenseReportsCreateNewResponse
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseReportsCreateNewResponse
     */
    'expenseReportId'?: string;
}

