/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModelUserModel } from './feedback-list-feedback-response-feedback-list-inner-assigned-user-model-department-model-user-model';

/**
 * 
 * @export
 * @interface FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel
 */
export interface FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel {
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel
     */
    'departmentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel
     */
    'deptHead'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel
     */
    'departmentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel
     */
    'departmentLabel'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel
     */
    'parentDepartmentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel
     */
    'parentDepartmentName'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel
     */
    'deptHeadName'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel
     */
    'noOfEmployees'?: string;
    /**
     * 
     * @type {FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModelUserModel}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel
     */
    'userModel'?: FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModelUserModel;
}

