/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelPracticeModel
 */
export interface FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelPracticeModel {
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelPracticeModel
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelPracticeModel
     */
    'practiceId'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelPracticeModel
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelPracticeModel
     */
    'practiceHead'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelPracticeModel
     */
    'userModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelPracticeModel
     */
    'createts'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelPracticeModel
     */
    'cid'?: string;
}

