/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModelAddressModelListInner } from './feedback-list-feedback-response-feedback-list-inner-assigned-user-model-location-model-address-model-list-inner';

/**
 * 
 * @export
 * @interface FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
 */
export interface FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel {
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
     */
    'locationId'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
     */
    'locationName'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
     */
    'locationDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
     */
    'locationType'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
     */
    'lattitude'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
     */
    'longitude'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
     */
    'locationUID'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
     */
    'workingDays'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
     */
    'locationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
     */
    'locationLabel'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
     */
    'parentLocationId'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
     */
    'createuserid'?: string;
    /**
     * 
     * @type {Array<FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModelAddressModelListInner>}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel
     */
    'addressModelList'?: Array<FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModelAddressModelListInner>;
}

