/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel } from './feedback-list-feedback-response-feedback-list-inner-assigned-user-model-department-model';
import { FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel } from './feedback-list-feedback-response-feedback-list-inner-assigned-user-model-location-model';
import { FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelPracticeModel } from './feedback-list-feedback-response-feedback-list-inner-assigned-user-model-practice-model';

/**
 * 
 * @export
 * @interface FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
 */
export interface FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel {
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'empId'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'position'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'shortName'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'displayFullName'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'userStartDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'cellPhone'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'userName'?: string;
    /**
     * 
     * @type {FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'departmentModel'?: FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelDepartmentModel;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'prefixSalutation'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'secondLastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'middleName'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'familySuffix'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'ptoannual'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'ptobalance'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'workerType'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'userDateOfBirth'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'im'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'createts'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'timezone'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'adpAssociateOID'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'practiceId'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'imageName'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'thumbnail'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'profileId'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'allocation'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'countryId'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'lastupdateuserid'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'lastupdatets'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'userDateFormat'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'hrPortal'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'userDisplayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'star'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'timecardPeriodPref'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'tosVersion'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'jobGrade'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'paId'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'appMenuId'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'calendarId'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'workingDays'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'hasAccess'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'notifications'?: string;
    /**
     * 
     * @type {FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'locationModel'?: FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelLocationModel;
    /**
     * 
     * @type {FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelPracticeModel}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'practiceModel'?: FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModelPracticeModel;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'azureObjectIdentifier'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'isView'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackListFeedbackResponseFeedbackListInnerAssignedUserModel
     */
    'view'?: string;
}

