/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GoalsGetGoalResponseProjectModelUserModel
 */
export interface GoalsGetGoalResponseProjectModelUserModel {
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'shortName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'thumbnail'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'jobTitle'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'departmentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'locationId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'department'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'profileId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'profileName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'timezone'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'userStartdate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'userEnddate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'cellPhone'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'empId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'userdateOfBirth'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'allocation'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'userdateFormat'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'star'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'imageName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'notes'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'im'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'createuserid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'countryId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'hasAccess'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'displayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModelUserModel
     */
    'id'?: string;
}

