/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GoalsGetGoalResponseAssignedUserModel } from './goals-get-goal-response-assigned-user-model';
import { GoalsGetGoalResponseGoalCollaborationModelInner } from './goals-get-goal-response-goal-collaboration-model-inner';
import { GoalsGetGoalResponseGoalTypeModel } from './goals-get-goal-response-goal-type-model';
import { GoalsGetGoalResponseProjectModel } from './goals-get-goal-response-project-model';
import { GoalsGetGoalResponseReviewerUserModel } from './goals-get-goal-response-reviewer-user-model';

/**
 * 
 * @export
 * @interface GoalsGetGoalResponse
 */
export interface GoalsGetGoalResponse {
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'summary'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'goalId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'additive'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'visibleToDirectReports'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'freezeGoal'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'isForward'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'companyGoal'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'elapsedTimeRatio'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'completionRatio'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'progressRatio'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'typecode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'predictiveIndex'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'objectiveId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'disposition'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'units'?: string;
    /**
     * 
     * @type {GoalsGetGoalResponseAssignedUserModel}
     * @memberof GoalsGetGoalResponse
     */
    'assignedUserModel'?: GoalsGetGoalResponseAssignedUserModel;
    /**
     * 
     * @type {GoalsGetGoalResponseReviewerUserModel}
     * @memberof GoalsGetGoalResponse
     */
    'reviewerUserModel'?: GoalsGetGoalResponseReviewerUserModel;
    /**
     * 
     * @type {Array<GoalsGetGoalResponseGoalCollaborationModelInner>}
     * @memberof GoalsGetGoalResponse
     */
    'goalCollaborationModel'?: Array<GoalsGetGoalResponseGoalCollaborationModelInner>;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'crediteatets'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'commentCrediteatets'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'commentDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'uname'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'hasGoalApprovalPermission'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'begindate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'goalWeightage'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'createuserid'?: string;
    /**
     * 
     * @type {number}
     * @memberof GoalsGetGoalResponse
     */
    'createts'?: number;
    /**
     * 
     * @type {GoalsGetGoalResponseProjectModel}
     * @memberof GoalsGetGoalResponse
     */
    'projectModel'?: GoalsGetGoalResponseProjectModel;
    /**
     * 
     * @type {GoalsGetGoalResponseGoalTypeModel}
     * @memberof GoalsGetGoalResponse
     */
    'goalTypeModel'?: GoalsGetGoalResponseGoalTypeModel;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'parentGoalId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'createUserId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'lastUpdateUserId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'projectid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'targetdate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'initialvalue'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'currentvalue'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponse
     */
    'goalvalue'?: string;
}

