/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GoalsGetGoalResponseReviewerUserModelDepartmentModelUserModel } from './goals-get-goal-response-reviewer-user-model-department-model-user-model';

/**
 * 
 * @export
 * @interface GoalsGetGoalResponseReviewerUserModelDepartmentModel
 */
export interface GoalsGetGoalResponseReviewerUserModelDepartmentModel {
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelDepartmentModel
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelDepartmentModel
     */
    'departmentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelDepartmentModel
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelDepartmentModel
     */
    'deptHead'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelDepartmentModel
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelDepartmentModel
     */
    'departmentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelDepartmentModel
     */
    'departmentLabel'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelDepartmentModel
     */
    'parentDepartmentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelDepartmentModel
     */
    'parentDepartmentName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelDepartmentModel
     */
    'deptHeadName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelDepartmentModel
     */
    'noOfEmployees'?: string;
    /**
     * 
     * @type {GoalsGetGoalResponseReviewerUserModelDepartmentModelUserModel}
     * @memberof GoalsGetGoalResponseReviewerUserModelDepartmentModel
     */
    'userModel'?: GoalsGetGoalResponseReviewerUserModelDepartmentModelUserModel;
}

