/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GoalsGetGoalResponseAssignedUserModelUserProfileModel
 */
export interface GoalsGetGoalResponseAssignedUserModelUserProfileModel {
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'profileId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'profileName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'profileDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'orgId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'profileResponsibilities'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'profileRequirements'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'salaryBandMin'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'salaryBandMax'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'salaryBandCurrency'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'managerProfileId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'managerProfileName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'customFieldValueModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'numberofUsers'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'createuserid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'careerPathwayModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'objectType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'objectName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseAssignedUserModelUserProfileModel
     */
    'objectid'?: string;
}

