/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GoalsGetGoalResponseReviewerUserModelLocationModelAddressModelListInnerCountryModel
 */
export interface GoalsGetGoalResponseReviewerUserModelLocationModelAddressModelListInnerCountryModel {
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModelAddressModelListInnerCountryModel
     */
    'countryId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModelAddressModelListInnerCountryModel
     */
    'countryName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModelAddressModelListInnerCountryModel
     */
    'iso2'?: string;
}

