/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GoalsGetGoalResponseGoalCollaborationModelInnerUserModelUserProfileModel } from './goals-get-goal-response-goal-collaboration-model-inner-user-model-user-profile-model';

/**
 * 
 * @export
 * @interface GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
 */
export interface GoalsGetGoalResponseGoalCollaborationModelInnerUserModel {
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'empId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'shortName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'displayFullName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'userName'?: string;
    /**
     * 
     * @type {GoalsGetGoalResponseGoalCollaborationModelInnerUserModelUserProfileModel}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'userProfileModel'?: GoalsGetGoalResponseGoalCollaborationModelInnerUserModelUserProfileModel;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'ptoannual'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'ptobalance'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'phone'?: string;
    /**
     * 
     * @type {number}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'createts'?: number;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'timezone'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'profileId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'allocation'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'lastupdatets'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'userdateFormat'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'hrPortal'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'star'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'timecardPeriodPref'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'languagePreference'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'hasAccess'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'notifications'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'isView'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInnerUserModel
     */
    'view'?: string;
}

