/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GoalsGetGoalResponseReviewerUserModelLocationModelAddressModelListInner } from './goals-get-goal-response-reviewer-user-model-location-model-address-model-list-inner';

/**
 * 
 * @export
 * @interface GoalsGetGoalResponseReviewerUserModelLocationModel
 */
export interface GoalsGetGoalResponseReviewerUserModelLocationModel {
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModel
     */
    'locationId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModel
     */
    'locationName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModel
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModel
     */
    'locationDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModel
     */
    'locationType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModel
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModel
     */
    'lattitude'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModel
     */
    'longitude'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModel
     */
    'locationUID'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModel
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModel
     */
    'workingDays'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModel
     */
    'locationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModel
     */
    'locationLabel'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModel
     */
    'parentLocationId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModel
     */
    'createuserid'?: string;
    /**
     * 
     * @type {Array<GoalsGetGoalResponseReviewerUserModelLocationModelAddressModelListInner>}
     * @memberof GoalsGetGoalResponseReviewerUserModelLocationModel
     */
    'addressModelList'?: Array<GoalsGetGoalResponseReviewerUserModelLocationModelAddressModelListInner>;
}

