/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GoalsGetGoalResponseProjectModelUserModel } from './goals-get-goal-response-project-model-user-model';

/**
 * 
 * @export
 * @interface GoalsGetGoalResponseProjectModel
 */
export interface GoalsGetGoalResponseProjectModel {
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'projectId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'projectName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'projectDesc'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'startdate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'enddate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'contactPerson'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'account'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'accountModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'userModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'createts'?: number;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'shortCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'probability'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'contactPersonName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'statusValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'pgroupid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'puid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'billingType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'timeSheetOpenToAll'?: string;
    /**
     * 
     * @type {GoalsGetGoalResponseProjectModelUserModel}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'userModel'?: GoalsGetGoalResponseProjectModelUserModel;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'projectGroupModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'groupName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'accountName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'pmMail'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'locationid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'reportMethod'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'industry'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'isAdmin'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'createuserid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'lastupdateuserid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'admin'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'projStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseProjectModel
     */
    'projProbability'?: string;
}

