/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GoalsGetGoalResponseGoalCollaborationModelInnerUserModel } from './goals-get-goal-response-goal-collaboration-model-inner-user-model';

/**
 * 
 * @export
 * @interface GoalsGetGoalResponseGoalCollaborationModelInner
 */
export interface GoalsGetGoalResponseGoalCollaborationModelInner {
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInner
     */
    'collabid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInner
     */
    'goalid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInner
     */
    'userid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInner
     */
    'extuserid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInner
     */
    'cid'?: string;
    /**
     * 
     * @type {GoalsGetGoalResponseGoalCollaborationModelInnerUserModel}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInner
     */
    'userModel'?: GoalsGetGoalResponseGoalCollaborationModelInnerUserModel;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalCollaborationModelInner
     */
    'extuserModel'?: string;
}

