/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GoalsGetGoalResponseReviewerUserModelDepartmentModel } from './goals-get-goal-response-reviewer-user-model-department-model';
import { GoalsGetGoalResponseReviewerUserModelLocationModel } from './goals-get-goal-response-reviewer-user-model-location-model';

/**
 * 
 * @export
 * @interface GoalsGetGoalResponseReviewerUserModel
 */
export interface GoalsGetGoalResponseReviewerUserModel {
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'empId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'position'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'shortName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'displayFullName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'userStartdate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'cellPhone'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'userName'?: string;
    /**
     * 
     * @type {GoalsGetGoalResponseReviewerUserModelDepartmentModel}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'departmentModel'?: GoalsGetGoalResponseReviewerUserModelDepartmentModel;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'prefixSalutation'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'middleName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'familySuffix'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'ptoannual'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'ptobalance'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'workerType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'im'?: string;
    /**
     * 
     * @type {number}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'createts'?: number;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'timezone'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'profileId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'allocation'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'lastupdateuserid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'lastupdatets'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'userdateFormat'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'hrPortal'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'userDisplayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'star'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'timecardPeriodPref'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'tosVersion'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'jobGrade'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'calendarId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'workingDays'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'hasAccess'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'notifications'?: string;
    /**
     * 
     * @type {GoalsGetGoalResponseReviewerUserModelLocationModel}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'locationModel'?: GoalsGetGoalResponseReviewerUserModelLocationModel;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'isView'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseReviewerUserModel
     */
    'view'?: string;
}

