/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GoalsGetGoalResponseGoalTypeModelAssessmentModel } from './goals-get-goal-response-goal-type-model-assessment-model';

/**
 * 
 * @export
 * @interface GoalsGetGoalResponseGoalTypeModel
 */
export interface GoalsGetGoalResponseGoalTypeModel {
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalTypeModel
     */
    'goalTypeId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalTypeModel
     */
    'goalTypeName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalTypeModel
     */
    'goalTypeDescription'?: string;
    /**
     * 
     * @type {GoalsGetGoalResponseGoalTypeModelAssessmentModel}
     * @memberof GoalsGetGoalResponseGoalTypeModel
     */
    'assessmentModel'?: GoalsGetGoalResponseGoalTypeModelAssessmentModel;
    /**
     * 
     * @type {number}
     * @memberof GoalsGetGoalResponseGoalTypeModel
     */
    'createts'?: number;
    /**
     * 
     * @type {string}
     * @memberof GoalsGetGoalResponseGoalTypeModel
     */
    'cid'?: string;
}

