/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InvoiceGetByProjectIdResponse
 */
export interface InvoiceGetByProjectIdResponse {
    /**
     * 
     * @type {Array<object>}
     * @memberof InvoiceGetByProjectIdResponse
     */
    'data'?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof InvoiceGetByProjectIdResponse
     */
    'message'?: string;
}

