/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PtoPolicyModel } from './pto-policy-model';
import { UserModel } from './user-model';
import { UserViewModel } from './user-view-model';

/**
 * 
 * @export
 * @interface LeaveModel
 */
export interface LeaveModel {
    /**
     * Description for the leave.
     * @type {string}
     * @memberof LeaveModel
     */
    'description'?: string;
    /**
     * 
     * @type {UserViewModel}
     * @memberof LeaveModel
     */
    'createUserViewModel'?: UserViewModel;
    /**
     * Date of the leave.
     * @type {string}
     * @memberof LeaveModel
     */
    'date': string;
    /**
     * 
     * @type {string}
     * @memberof LeaveModel
     */
    'endDateMeridiem'?: string;
    /**
     * 
     * @type {string}
     * @memberof LeaveModel
     */
    'meridiem'?: string;
    /**
     * Number of days for which leave is requested.
     * @type {number}
     * @memberof LeaveModel
     */
    'numberOfDays'?: number;
    /**
     * 
     * @type {PtoPolicyModel}
     * @memberof LeaveModel
     */
    'ptoPolicyModel'?: PtoPolicyModel;
    /**
     * Total days of leave.
     * @type {number}
     * @memberof LeaveModel
     */
    'totalLeaveDays'?: number;
    /**
     * Total hours of leave.
     * @type {number}
     * @memberof LeaveModel
     */
    'totalLeaveHours'?: number;
    /**
     * 
     * @type {UserModel}
     * @memberof LeaveModel
     */
    'userModel'?: UserModel;
}

