/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Timestamp } from './timestamp';
import { UserModel } from './user-model';

/**
 * 
 * @export
 * @interface MailTemplateModel
 */
export interface MailTemplateModel {
    /**
     * 
     * @type {string}
     * @memberof MailTemplateModel
     */
    'title'?: string;
    /**
     * 
     * @type {number}
     * @memberof MailTemplateModel
     */
    'cid'?: number;
    /**
     * 
     * @type {string}
     * @memberof MailTemplateModel
     */
    'communicationType'?: string;
    /**
     * 
     * @type {UserModel}
     * @memberof MailTemplateModel
     */
    'createUserModel'?: UserModel;
    /**
     * 
     * @type {Timestamp}
     * @memberof MailTemplateModel
     */
    'createts'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof MailTemplateModel
     */
    'footerAdditionalInfo'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MailTemplateModel
     */
    'footerCompanyAddress'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MailTemplateModel
     */
    'footerCompanyLogo'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MailTemplateModel
     */
    'footerContentAlignmnet'?: string;
    /**
     * 
     * @type {string}
     * @memberof MailTemplateModel
     */
    'headerAdditionalInfo'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MailTemplateModel
     */
    'headerCompanyAddress'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MailTemplateModel
     */
    'headerCompanyLogo'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MailTemplateModel
     */
    'headerContentAlignment'?: string;
    /**
     * 
     * @type {Timestamp}
     * @memberof MailTemplateModel
     */
    'lastupdatets'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof MailTemplateModel
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof MailTemplateModel
     */
    'object'?: string;
    /**
     * 
     * @type {string}
     * @memberof MailTemplateModel
     */
    'subject'?: string;
    /**
     * 
     * @type {string}
     * @memberof MailTemplateModel
     */
    'systemUsage'?: string;
    /**
     * 
     * @type {number}
     * @memberof MailTemplateModel
     */
    'templateId'?: number;
}

