/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PeopleAndPermissionsGetUsersResponseDataInner } from './people-and-permissions-get-users-response-data-inner';

/**
 * 
 * @export
 * @interface PeopleAndPermissionsGetUsersResponse
 */
export interface PeopleAndPermissionsGetUsersResponse {
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetUsersResponse
     */
    'code'?: string;
    /**
     * 
     * @type {Array<PeopleAndPermissionsGetUsersResponseDataInner>}
     * @memberof PeopleAndPermissionsGetUsersResponse
     */
    'data'?: Array<PeopleAndPermissionsGetUsersResponseDataInner>;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetUsersResponse
     */
    'message'?: string;
}

