/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PeopleAndPermissionsSaveUserEducationRequestRAWBODYInner } from './people-and-permissions-save-user-education-request-rawbodyinner';

/**
 * 
 * @export
 * @interface PeopleAndPermissionsSaveUserEducationRequest
 */
export interface PeopleAndPermissionsSaveUserEducationRequest {
    /**
     * 
     * @type {Array<PeopleAndPermissionsSaveUserEducationRequestRAWBODYInner>}
     * @memberof PeopleAndPermissionsSaveUserEducationRequest
     */
    'RAW_BODY'?: Array<PeopleAndPermissionsSaveUserEducationRequestRAWBODYInner>;
}

