/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInner
 */
export interface PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInner {
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInner
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInner
     */
    'relationToUser'?: PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInnerRelationToUserEnum;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInner
     */
    'contactType'?: PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInnerContactTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInner
     */
    'gender'?: PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInnerGenderEnum;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInner
     */
    'taxNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInner
     */
    'dateOfBirth'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInner
     */
    'status'?: PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInnerStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInner
     */
    'extAppUID'?: string;
}

type PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInnerRelationToUserEnum = 'Spouse' | 'Parent' | 'Child' | 'Other'
type PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInnerContactTypeEnum = 'DEP' | 'ECON' | 'ACCT'
type PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInnerGenderEnum = 'M' | 'F' | 'H'
type PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInnerStatusEnum = 'AP' | 'WA'


