/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PeopleAndPermissionsCreateOrUpdateUserDetailsRequestAddressListInner } from './people-and-permissions-create-or-update-user-details-request-address-list-inner';
import { PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInner } from './people-and-permissions-create-or-update-user-details-request-contact-list-inner';
import { PeopleAndPermissionsCreateOrUpdateUserDetailsRequestEducationListInner } from './people-and-permissions-create-or-update-user-details-request-education-list-inner';
import { PeopleAndPermissionsCreateOrUpdateUserDetailsRequestFinancialListInner } from './people-and-permissions-create-or-update-user-details-request-financial-list-inner';

/**
 * 
 * @export
 * @interface PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
 */
export interface PeopleAndPermissionsCreateOrUpdateUserDetailsRequest {
    /**
     * First name of user.
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'firstName'?: string;
    /**
     * Mail ID of user.
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'email'?: string;
    /**
     * Last name of user.
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'lastName'?: string;
    /**
     * Employee ID of the user.
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'empId'?: string;
    /**
     * Gender of the user.
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'gender'?: string;
    /**
     * The unique system generated ID of the user.
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'guid'?: string;
    /**
     * Status of the user. A - Active, I - Inactive, F - Future Joiner
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'status'?: PeopleAndPermissionsCreateOrUpdateUserDetailsRequestStatusEnum;
    /**
     * Display name of the user.
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'displayFullName'?: string;
    /**
     * Middle name of user.
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'middleName'?: string;
    /**
     * Second Last name of user.
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'secondLastName'?: string;
    /**
     * Short name of user.
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'shortName'?: string;
    /**
     * Name Pronunciation
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'namePronunciation'?: string;
    /**
     * Family Suffix
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'familySuffix'?: string;
    /**
     * Worker type of the user.
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'workerType'?: string;
    /**
     * Birth date of user.
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'userDateOfBirth'?: string;
    /**
     * Phone number of the user.
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'phone'?: string;
    /**
     * Cell phone of the user.
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'cellPhone'?: string;
    /**
     * Profile ID of the user.
     * @type {number}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'position'?: number;
    /**
     * Org Unit ID of the user.
     * @type {number}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'departmentID'?: number;
    /**
     * Location ID of the user.
     * @type {number}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'locationId'?: number;
    /**
     * Location of user.
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'locationName'?: string;
    /**
     * Start Date of user.
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'userStartDate'?: string;
    /**
     * Managers detail of user.
     * @type {Array<string>}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'reportsToEmail'?: Array<string>;
    /**
     * Address detail of user.
     * @type {Array<PeopleAndPermissionsCreateOrUpdateUserDetailsRequestAddressListInner>}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'addressList'?: Array<PeopleAndPermissionsCreateOrUpdateUserDetailsRequestAddressListInner>;
    /**
     * Education detail of user.
     * @type {Array<PeopleAndPermissionsCreateOrUpdateUserDetailsRequestEducationListInner>}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'educationList'?: Array<PeopleAndPermissionsCreateOrUpdateUserDetailsRequestEducationListInner>;
    /**
     * Contact detail of user
     * @type {Array<PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInner>}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'contactList'?: Array<PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInner>;
    /**
     * Financial detail of user.
     * @type {Array<PeopleAndPermissionsCreateOrUpdateUserDetailsRequestFinancialListInner>}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'financialList'?: Array<PeopleAndPermissionsCreateOrUpdateUserDetailsRequestFinancialListInner>;
    /**
     * key - cfcode , value - cfvalue
     * @type {string}
     * @memberof PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    'customFieldValues'?: string;
}

type PeopleAndPermissionsCreateOrUpdateUserDetailsRequestStatusEnum = 'A' | 'I' | 'F'


