/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PeopleAndPermissionsGetAllUsersDetailsResponseInnerSupervisorModelListInner
 */
export interface PeopleAndPermissionsGetAllUsersDetailsResponseInnerSupervisorModelListInner {
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInnerSupervisorModelListInner
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInnerSupervisorModelListInner
     */
    'firstName'?: string;
    /**
     * The unique identity of the employee. 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInnerSupervisorModelListInner
     */
    'empId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInnerSupervisorModelListInner
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInnerSupervisorModelListInner
     */
    'middleName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInnerSupervisorModelListInner
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInnerSupervisorModelListInner
     */
    'displayFullName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInnerSupervisorModelListInner
     */
    'userStartDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInnerSupervisorModelListInner
     */
    'locationId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInnerSupervisorModelListInner
     */
    'departmentID'?: string;
}

