/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PeopleAndPermissionsGetAllUsersDetailsResponseInnerSupervisorModelListInner } from './people-and-permissions-get-all-users-details-response-inner-supervisor-model-list-inner';

/**
 * 
 * @export
 * @interface PeopleAndPermissionsGetAllUsersDetailsResponseInner
 */
export interface PeopleAndPermissionsGetAllUsersDetailsResponseInner {
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'shortName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'displayFullName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'userStartDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'cellPhone'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'userName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'employmentModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'educationModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'licenseModelList'?: string;
    /**
     * 
     * @type {Array<PeopleAndPermissionsGetAllUsersDetailsResponseInnerSupervisorModelListInner>}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'supervisorModelList'?: Array<PeopleAndPermissionsGetAllUsersDetailsResponseInnerSupervisorModelListInner>;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'awardModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'addressModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'customFieldValueModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'createts'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'financialModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'allocation'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'userDisplayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'star'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsGetAllUsersDetailsResponseInner
     */
    'isView'?: string;
}

