/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PeopleAndPermissionsSaveUserAddressRequestRAWBODYInner } from './people-and-permissions-save-user-address-request-rawbodyinner';

/**
 * 
 * @export
 * @interface PeopleAndPermissionsSaveUserAddressRequest
 */
export interface PeopleAndPermissionsSaveUserAddressRequest {
    /**
     * 
     * @type {Array<PeopleAndPermissionsSaveUserAddressRequestRAWBODYInner>}
     * @memberof PeopleAndPermissionsSaveUserAddressRequest
     */
    'RAW_BODY'?: Array<PeopleAndPermissionsSaveUserAddressRequestRAWBODYInner>;
}

