/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PeopleAndPermissionsUploadUserProfilePictureResponse
 */
export interface PeopleAndPermissionsUploadUserProfilePictureResponse {
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsUploadUserProfilePictureResponse
     */
    'imageName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsUploadUserProfilePictureResponse
     */
    'data'?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleAndPermissionsUploadUserProfilePictureResponse
     */
    'message'?: string;
}

