/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PerformanceReviewCreatePerformanceReviewResponse
 */
export interface PerformanceReviewCreatePerformanceReviewResponse {
    /**
     * 
     * @type {string}
     * @memberof PerformanceReviewCreatePerformanceReviewResponse
     */
    'appraisalId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PerformanceReviewCreatePerformanceReviewResponse
     */
    'message'?: string;
}

