/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CandidateApplicationsModel } from './candidate-applications-model';
import { LocationModel } from './location-model';
import { PositionApprovalLevelModel } from './position-approval-level-model';
import { ProjectModel } from './project-model';
import { UserPositionApprovalModel } from './user-position-approval-model';
import { UserProfileModel } from './user-profile-model';
import { UserViewModel } from './user-view-model';

/**
 * 
 * @export
 * @interface PositionModel
 */
export interface PositionModel {
    /**
     * 
     * @type {string}
     * @memberof PositionModel
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof PositionModel
     */
    'accessLevel'?: string;
    /**
     * 
     * @type {string}
     * @memberof PositionModel
     */
    'applicationDueDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'applicationFormId'?: number;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'approvalFlowId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PositionModel
     */
    'approvalStatus'?: string;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'assessmentFormId'?: number;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'assessmentTemplateId'?: number;
    /**
     * 
     * @type {Array<CandidateApplicationsModel>}
     * @memberof PositionModel
     */
    'candidatePositionModelList'?: Array<CandidateApplicationsModel>;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'cid'?: number;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof PositionModel
     */
    'createDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'createUserId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PositionModel
     */
    'customLocation'?: string;
    /**
     * 
     * @type {string}
     * @memberof PositionModel
     */
    'dateClose'?: string;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'departmentId'?: number;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'funnelId'?: number;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'hiringManagerId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PositionModel
     */
    'htmlTemplate'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PositionModel
     */
    'isRecommended'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PositionModel
     */
    'lastUpdatets'?: string;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'lastupdateuserid'?: number;
    /**
     * 
     * @type {LocationModel}
     * @memberof PositionModel
     */
    'locationModel'?: LocationModel;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'locationid'?: number;
    /**
     * 
     * @type {string}
     * @memberof PositionModel
     */
    'name'?: string;
    /**
     * 
     * @type {Array<PositionApprovalLevelModel>}
     * @memberof PositionModel
     */
    'positionApprovalLevelList'?: Array<PositionApprovalLevelModel>;
    /**
     * 
     * @type {string}
     * @memberof PositionModel
     */
    'positionUID'?: string;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'positionid'?: number;
    /**
     * 
     * @type {UserProfileModel}
     * @memberof PositionModel
     */
    'profileModel'?: UserProfileModel;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'profileid'?: number;
    /**
     * 
     * @type {ProjectModel}
     * @memberof PositionModel
     */
    'projectModel'?: ProjectModel;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'projectid'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PositionModel
     */
    'recommended'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'recruiterId'?: number;
    /**
     * 
     * @type {UserViewModel}
     * @memberof PositionModel
     */
    'recruiterModel'?: UserViewModel;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'requestApprovalId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PositionModel
     */
    'requirements'?: string;
    /**
     * 
     * @type {string}
     * @memberof PositionModel
     */
    'responsibilities'?: string;
    /**
     * 
     * @type {string}
     * @memberof PositionModel
     */
    'seoUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof PositionModel
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'totalcandidate'?: number;
    /**
     * 
     * @type {string}
     * @memberof PositionModel
     */
    'userName'?: string;
    /**
     * 
     * @type {UserViewModel}
     * @memberof PositionModel
     */
    'userViewModel'?: UserViewModel;
    /**
     * 
     * @type {Array<UserPositionApprovalModel>}
     * @memberof PositionModel
     */
    'userapprovalList'?: Array<UserPositionApprovalModel>;
    /**
     * 
     * @type {number}
     * @memberof PositionModel
     */
    'id'?: number;
}

