/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PositionStatusModel
 */
export interface PositionStatusModel {
    /**
     * 
     * @type {number}
     * @memberof PositionStatusModel
     */
    'cid'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PositionStatusModel
     */
    'defaultStatus'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PositionStatusModel
     */
    'internalStatus'?: string;
    /**
     * 
     * @type {number}
     * @memberof PositionStatusModel
     */
    'statusId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PositionStatusModel
     */
    'statusName'?: string;
}

