/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccountModel } from './account-model';
import { ProjectGroupModel } from './project-group-model';
import { Timestamp } from './timestamp';
import { UserModel } from './user-model';
import { UserViewModel } from './user-view-model';

/**
 * 
 * @export
 * @interface ProjectModel
 */
export interface ProjectModel {
    /**
     * 
     * @type {number}
     * @memberof ProjectModel
     */
    'Probability'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectModel
     */
    'account'?: number;
    /**
     * 
     * @type {AccountModel}
     * @memberof ProjectModel
     */
    'accountModel'?: AccountModel;
    /**
     * 
     * @type {string}
     * @memberof ProjectModel
     */
    'accountName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectModel
     */
    'billing_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectModel
     */
    'cid'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectModel
     */
    'contactPerson'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectModel
     */
    'contactPersonName'?: string;
    /**
     * 
     * @type {Timestamp}
     * @memberof ProjectModel
     */
    'createts'?: Timestamp;
    /**
     * 
     * @type {number}
     * @memberof ProjectModel
     */
    'createuserid'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectModel
     */
    'endDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectModel
     */
    'groupName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectModel
     */
    'industry'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectModel
     */
    'lastupdateuserid'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectModel
     */
    'locationid'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectModel
     */
    'pgroupid'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectModel
     */
    'pmMail'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectModel
     */
    'probability'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectModel
     */
    'projProbability'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectModel
     */
    'projStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectModel
     */
    'projectDesc'?: string;
    /**
     * 
     * @type {ProjectGroupModel}
     * @memberof ProjectModel
     */
    'projectGroupModel'?: ProjectGroupModel;
    /**
     * 
     * @type {number}
     * @memberof ProjectModel
     */
    'projectId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectModel
     */
    'projectName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectModel
     */
    'puid'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectModel
     */
    'reportMethod'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectModel
     */
    'shortCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectModel
     */
    'startDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectModel
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectModel
     */
    'statusValue'?: string;
    /**
     * 
     * @type {UserViewModel}
     * @memberof ProjectModel
     */
    'userModel'?: UserViewModel;
    /**
     * 
     * @type {Array<UserModel>}
     * @memberof ProjectModel
     */
    'userModelList'?: Array<UserModel>;
}

