/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProjectGroupModel
 */
export interface ProjectGroupModel {
    /**
     * 
     * @type {number}
     * @memberof ProjectGroupModel
     */
    'cid'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectGroupModel
     */
    'groupDesc'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectGroupModel
     */
    'groupName'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectGroupModel
     */
    'pgroupid'?: number;
}

