/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserGroupModel } from './user-group-model';

/**
 * 
 * @export
 * @interface PtoPolicyApprovalModel
 */
export interface PtoPolicyApprovalModel {
    /**
     * 
     * @type {number}
     * @memberof PtoPolicyApprovalModel
     */
    'approvalId'?: number;
    /**
     * 
     * @type {number}
     * @memberof PtoPolicyApprovalModel
     */
    'cid'?: number;
    /**
     * 
     * @type {number}
     * @memberof PtoPolicyApprovalModel
     */
    'createUserId'?: number;
    /**
     * 
     * @type {number}
     * @memberof PtoPolicyApprovalModel
     */
    'flowId'?: number;
    /**
     * 
     * @type {number}
     * @memberof PtoPolicyApprovalModel
     */
    'levelSequence'?: number;
    /**
     * 
     * @type {string}
     * @memberof PtoPolicyApprovalModel
     */
    'relationType'?: string;
    /**
     * 
     * @type {number}
     * @memberof PtoPolicyApprovalModel
     */
    'skippable'?: number;
    /**
     * 
     * @type {UserGroupModel}
     * @memberof PtoPolicyApprovalModel
     */
    'userGroupModel'?: UserGroupModel;
}

