/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PtoPolicyApprovalModel } from './pto-policy-approval-model';
import { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface PtoPolicyApprovalFlowModel
 */
export interface PtoPolicyApprovalFlowModel {
    /**
     * 
     * @type {string}
     * @memberof PtoPolicyApprovalFlowModel
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof PtoPolicyApprovalFlowModel
     */
    'cid'?: number;
    /**
     * 
     * @type {Timestamp}
     * @memberof PtoPolicyApprovalFlowModel
     */
    'createts'?: Timestamp;
    /**
     * 
     * @type {number}
     * @memberof PtoPolicyApprovalFlowModel
     */
    'flowId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PtoPolicyApprovalFlowModel
     */
    'flowName'?: string;
    /**
     * 
     * @type {Array<PtoPolicyApprovalModel>}
     * @memberof PtoPolicyApprovalFlowModel
     */
    'ptoPolicyApprovalModelList'?: Array<PtoPolicyApprovalModel>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PtoPolicyApprovalFlowModel
     */
    'ptoPolicyList'?: Array<string>;
}

