/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReportsGetContentForReportResponseDataInnerEntityListInner } from './reports-get-content-for-report-response-data-inner-entity-list-inner';

/**
 * 
 * @export
 * @interface ReportsGetContentForReportResponseDataInner
 */
export interface ReportsGetContentForReportResponseDataInner {
    /**
     * 
     * @type {Array<ReportsGetContentForReportResponseDataInnerEntityListInner>}
     * @memberof ReportsGetContentForReportResponseDataInner
     */
    'entityList'?: Array<ReportsGetContentForReportResponseDataInnerEntityListInner>;
}

