/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SkillsGetUserAssignedSkillsResponseDataInner } from './skills-get-user-assigned-skills-response-data-inner';

/**
 * 
 * @export
 * @interface SkillsGetUserAssignedSkillsResponse
 */
export interface SkillsGetUserAssignedSkillsResponse {
    /**
     * 
     * @type {Array<SkillsGetUserAssignedSkillsResponseDataInner>}
     * @memberof SkillsGetUserAssignedSkillsResponse
     */
    'data'?: Array<SkillsGetUserAssignedSkillsResponseDataInner>;
    /**
     * 
     * @type {string}
     * @memberof SkillsGetUserAssignedSkillsResponse
     */
    'message'?: string;
}

