/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SkillViewModel } from './skill-view-model';

/**
 * 
 * @export
 * @interface SkillTypeModel
 */
export interface SkillTypeModel {
    /**
     * 
     * @type {number}
     * @memberof SkillTypeModel
     */
    'cid'?: number;
    /**
     * 
     * @type {number}
     * @memberof SkillTypeModel
     */
    'createUserId'?: number;
    /**
     * 
     * @type {string}
     * @memberof SkillTypeModel
     */
    'createts'?: string;
    /**
     * 
     * @type {string}
     * @memberof SkillTypeModel
     */
    'skillTypeDesc'?: string;
    /**
     * 
     * @type {number}
     * @memberof SkillTypeModel
     */
    'skillTypeId'?: number;
    /**
     * 
     * @type {string}
     * @memberof SkillTypeModel
     */
    'skillTypeName'?: string;
    /**
     * 
     * @type {Array<SkillViewModel>}
     * @memberof SkillTypeModel
     */
    'skillViewModelList'?: Array<SkillViewModel>;
}

