/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SkillModel } from './skill-model';
import { Timestamp } from './timestamp';
import { UserModel } from './user-model';

/**
 * 
 * @export
 * @interface SkillUserModel
 */
export interface SkillUserModel {
    /**
     * 
     * @type {string}
     * @memberof SkillUserModel
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof SkillUserModel
     */
    'candidateid'?: number;
    /**
     * 
     * @type {number}
     * @memberof SkillUserModel
     */
    'cid'?: number;
    /**
     * 
     * @type {number}
     * @memberof SkillUserModel
     */
    'createUserId'?: number;
    /**
     * 
     * @type {Timestamp}
     * @memberof SkillUserModel
     */
    'createts'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof SkillUserModel
     */
    'dateOfLastUse'?: string;
    /**
     * 
     * @type {UserModel}
     * @memberof SkillUserModel
     */
    'lastUpdateUserModel'?: UserModel;
    /**
     * 
     * @type {number}
     * @memberof SkillUserModel
     */
    'level'?: number;
    /**
     * 
     * @type {number}
     * @memberof SkillUserModel
     */
    'performancelevel'?: number;
    /**
     * 
     * @type {string}
     * @memberof SkillUserModel
     */
    'skillAcquireDate'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SkillUserModel
     */
    'skillCounsellor'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SkillUserModel
     */
    'skillId'?: number;
    /**
     * 
     * @type {SkillModel}
     * @memberof SkillUserModel
     */
    'skillModel'?: SkillModel;
    /**
     * 
     * @type {number}
     * @memberof SkillUserModel
     */
    'skillUserId'?: number;
    /**
     * 
     * @type {string}
     * @memberof SkillUserModel
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof SkillUserModel
     */
    'targetLevel'?: number;
    /**
     * 
     * @type {number}
     * @memberof SkillUserModel
     */
    'targetLevelCreateUserId'?: number;
    /**
     * 
     * @type {Timestamp}
     * @memberof SkillUserModel
     */
    'targetLevelCreatets'?: Timestamp;
    /**
     * 
     * @type {number}
     * @memberof SkillUserModel
     */
    'userId'?: number;
    /**
     * 
     * @type {number}
     * @memberof SkillUserModel
     */
    'weightage'?: number;
    /**
     * 
     * @type {number}
     * @memberof SkillUserModel
     */
    'yearsOfExperience'?: number;
}

