/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SkillsGetSkillsResponseInner
 */
export interface SkillsGetSkillsResponseInner {
    /**
     * 
     * @type {string}
     * @memberof SkillsGetSkillsResponseInner
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof SkillsGetSkillsResponseInner
     */
    'sequence'?: string;
    /**
     * 
     * @type {string}
     * @memberof SkillsGetSkillsResponseInner
     */
    'createUserId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SkillsGetSkillsResponseInner
     */
    'skillCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof SkillsGetSkillsResponseInner
     */
    'createts'?: string;
    /**
     * 
     * @type {string}
     * @memberof SkillsGetSkillsResponseInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SkillsGetSkillsResponseInner
     */
    'status'?: string;
}

