/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SkillsGetSkills401Response
 */
export interface SkillsGetSkills401Response {
    /**
     * 
     * @type {string}
     * @memberof SkillsGetSkills401Response
     */
    'message'?: string;
}

