/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SkillsCreateNewSkillRequestAssessmentModelRangeModelListInner
 */
export interface SkillsCreateNewSkillRequestAssessmentModelRangeModelListInner {
    /**
     * Description of the range.
     * @type {string}
     * @memberof SkillsCreateNewSkillRequestAssessmentModelRangeModelListInner
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof SkillsCreateNewSkillRequestAssessmentModelRangeModelListInner
     */
    'interpretation'?: string;
    /**
     * Maximum range.
     * @type {number}
     * @memberof SkillsCreateNewSkillRequestAssessmentModelRangeModelListInner
     */
    'rangeMax'?: number;
    /**
     * Minimum range.
     * @type {number}
     * @memberof SkillsCreateNewSkillRequestAssessmentModelRangeModelListInner
     */
    'rangeMin'?: number;
    /**
     * The ID of the assessment scale.
     * @type {number}
     * @memberof SkillsCreateNewSkillRequestAssessmentModelRangeModelListInner
     */
    'scoreTempId'?: number;
    /**
     * 
     * @type {number}
     * @memberof SkillsCreateNewSkillRequestAssessmentModelRangeModelListInner
     */
    'strangeid'?: number;
}

