/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TimesheetsGetActiveAllocationsResponseDataInner
 */
export interface TimesheetsGetActiveAllocationsResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'projectId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'projectName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'projectDesc'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'startDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'endDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'contactPerson'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'account'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'createts'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'shortCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'probability'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'contactPersonName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'statusValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'puid'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'billingType'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'timeSheetOpenToAll'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'projectGroupModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'locationModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'customFieldValueModelList'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetActiveAllocationsResponseDataInner
     */
    'billinCategoryModels'?: string;
}

