/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TimesheetsGetApprovalListResponseDataInner } from './timesheets-get-approval-list-response-data-inner';

/**
 * 
 * @export
 * @interface TimesheetsGetApprovalListResponse
 */
export interface TimesheetsGetApprovalListResponse {
    /**
     * 
     * @type {Array<TimesheetsGetApprovalListResponseDataInner>}
     * @memberof TimesheetsGetApprovalListResponse
     */
    'data'?: Array<TimesheetsGetApprovalListResponseDataInner>;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponse
     */
    'message'?: string;
}

