/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TimesheetsClockIn409Response
 */
export interface TimesheetsClockIn409Response {
    /**
     * 
     * @type {string}
     * @memberof TimesheetsClockIn409Response
     */
    'message'?: string;
}

