/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TimesheetsListActivityTypesByCidResponseDataInner
 */
export interface TimesheetsListActivityTypesByCidResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof TimesheetsListActivityTypesByCidResponseDataInner
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsListActivityTypesByCidResponseDataInner
     */
    'activityId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsListActivityTypesByCidResponseDataInner
     */
    'activityType'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsListActivityTypesByCidResponseDataInner
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsListActivityTypesByCidResponseDataInner
     */
    'cid'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsListActivityTypesByCidResponseDataInner
     */
    'createts'?: string;
}

