/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Timestamp
 */
export interface Timestamp {
    /**
     * 
     * @type {number}
     * @memberof Timestamp
     */
    'date'?: number;
    /**
     * 
     * @type {number}
     * @memberof Timestamp
     */
    'hours'?: number;
    /**
     * 
     * @type {number}
     * @memberof Timestamp
     */
    'minutes'?: number;
    /**
     * 
     * @type {number}
     * @memberof Timestamp
     */
    'month'?: number;
    /**
     * 
     * @type {number}
     * @memberof Timestamp
     */
    'nanos'?: number;
    /**
     * 
     * @type {number}
     * @memberof Timestamp
     */
    'seconds'?: number;
    /**
     * 
     * @type {number}
     * @memberof Timestamp
     */
    'time'?: number;
    /**
     * 
     * @type {number}
     * @memberof Timestamp
     */
    'year'?: number;
    /**
     * 
     * @type {number}
     * @memberof Timestamp
     */
    'day'?: number;
    /**
     * 
     * @type {number}
     * @memberof Timestamp
     */
    'timezoneOffset'?: number;
}

