/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TimecardsGetByUserId200Response
 */
export interface TimecardsGetByUserId200Response {
    /**
     * 
     * @type {string}
     * @memberof TimecardsGetByUserId200Response
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimecardsGetByUserId200Response
     */
    'createUserID'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimecardsGetByUserId200Response
     */
    'startDateTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimecardsGetByUserId200Response
     */
    'cardId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimecardsGetByUserId200Response
     */
    'createts'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimecardsGetByUserId200Response
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimecardsGetByUserId200Response
     */
    'endDateTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimecardsGetByUserId200Response
     */
    'projectId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimecardsGetByUserId200Response
     */
    'elapsedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimecardsGetByUserId200Response
     */
    'cid'?: string;
}

