/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TimesheetsGetApprovalListResponseDataInner
 */
export interface TimesheetsGetApprovalListResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'timesheetId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'startDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'endDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'userName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'empId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'orgUnit'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'departmentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'locationId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'locationName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'userStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'approvalFlowId'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'cardsCount'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'totalTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'leaveHours'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'holidayHours'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimesheetsGetApprovalListResponseDataInner
     */
    'cid'?: string;
}

