/*
Expense Reports

API Documentation

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Timestamp } from './timestamp';

/**
 * 
 * @export
 * @interface WorkflowParameterModel
 */
export interface WorkflowParameterModel {
    /**
     * 
     * @type {number}
     * @memberof WorkflowParameterModel
     */
    'cid'?: number;
    /**
     * 
     * @type {Timestamp}
     * @memberof WorkflowParameterModel
     */
    'createts'?: Timestamp;
    /**
     * 
     * @type {string}
     * @memberof WorkflowParameterModel
     */
    'paramName'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowParameterModel
     */
    'paramType'?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkflowParameterModel
     */
    'workflowArgId'?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkflowParameterModel
     */
    'workflowId'?: number;
}

